export const PROGRAM_CATEGORIES = [
  'Bodybuilding',
  'Strength Training',
  'Powerlifting',
  'Olympic Weightlifting',
  'Functional Fitness',
  'CrossFit',
  'High-Intensity Interval Training (HIIT)',
  'Cardio',
  'Endurance Training',
  'Running',
  'Swimming',
  'Cycling',
  'Yoga',
  'Pilates',
  'Barre',
  'Dance Fitness',
  'Kickboxing',
  'Boxing',
  'Martial Arts',
  'Calisthenics',
  'Stretching',
  'Flexibility Training',
  'Core Training',
  'Stability Training',
  'Balance Training',
  'Agility Training',
  'Speed Training',
  'Plyometrics',
  'Sports Performance',
  'Injury Prevention',
  'Rehabilitation',
  'Pre-natal Fitness',
  'Post-natal Fitness',
  'Senior Fitness',
  'Outdoor Fitness',
  'Adventure Racing',
  'Obstacle Course Racing',
  'Triathlon',
  'Duathlon',
  'Aquatic Fitness',
  'Surfing',
  'Kayaking',
  'Rowing',
  'Rock Climbing',
  'Hiking',
  'Trail Running',
  'Skiing',
  'Snowboarding',
  'Inline Skating',
  'Skateboarding',
  'Parkour',
];
