import {
  GOOGLE_MAPS_API_KEY as GOOGLE_MAPS_API_KEY_PROD,
  STRIPE_URL_SCHEME as STRIPE_URL_SCHEME_PROD,
  STRIPE_PUBLISHABLE_KEY as STRIPE_PUBLISHABLE_KEY_PROD,
  STRIPE_MERCHANT_IDENTIFIER as STRIPE_MERCHANT_IDENTIFIER_PROD,
  STRIPE_SECRET_KEY as STRIPE_SECRET_KEY_PROD,
  LUPA_MEETING_SERVICE_FEE_PERCENTAGE as LUPA_MEETING_SERVICE_FEE_PERCENTAGE_PROD,
  LUPA_PROGRAM_SERVICE_FEE_PERCENTAGE as LUPA_PROGRAM_SERVICE_FEE_PERCENTAGE_PROD,
  FIREBASE_API_KEY as FIREBASE_API_KEY_PROD,
  FIREBASE_AUTH_DOMAIN as FIREBASE_AUTH_DOMAIN_PROD,
  FIREBASE_PROJECT_ID as FIREBASE_PROJECT_ID_PROD,
  FIREBASE_STORAGE_BUCKET as FIREBASE_STORAGE_BUCKET_PROD,
  FIREBASE_MESSAGING_SENDER_ID as FIREBASE_MESSAGING_SENDER_ID_PROD,
  FIREBASE_APP_ID as FIREBASE_APP_ID_PROD,
  FIREBASE_MEASUREMENT_ID as FIREBASE_MEASUREMENT_ID_PROD,
} from '@env';

import {
  GOOGLE_MAPS_API_KEY as GOOGLE_MAPS_API_KEY_DEV,
  STRIPE_URL_SCHEME as STRIPE_URL_SCHEME_DEV,
  STRIPE_PUBLISHABLE_KEY as STRIPE_PUBLISHABLE_KEY_DEV,
  STRIPE_MERCHANT_IDENTIFIER as STRIPE_MERCHANT_IDENTIFIER_DEV,
  STRIPE_SECRET_KEY as STRIPE_SECRET_KEY_DEV,
  LUPA_MEETING_SERVICE_FEE_PERCENTAGE as LUPA_MEETING_SERVICE_FEE_PERCENTAGE_DEV,
  LUPA_PROGRAM_SERVICE_FEE_PERCENTAGE as LUPA_PROGRAM_SERVICE_FEE_PERCENTAGE_DEV,
  FIREBASE_API_KEY as FIREBASE_API_KEY_DEV,
  FIREBASE_AUTH_DOMAIN as FIREBASE_AUTH_DOMAIN_DEV,
  FIREBASE_PROJECT_ID as FIREBASE_PROJECT_ID_DEV,
  FIREBASE_STORAGE_BUCKET as FIREBASE_STORAGE_BUCKET_DEV,
  FIREBASE_MESSAGING_SENDER_ID as FIREBASE_MESSAGING_SENDER_ID_DEV,
  FIREBASE_APP_ID as FIREBASE_APP_ID_DEV,
  FIREBASE_MEASUREMENT_ID as FIREBASE_MEASUREMENT_ID_DEV,
} from '@envDevelopment';

export const getGoogleMapsAPIKey = (): string | null => {
  return process.env.NODE_ENV === 'production'
    ? GOOGLE_MAPS_API_KEY_PROD
    : GOOGLE_MAPS_API_KEY_DEV;
};

export const STRIPE_URL_SCHEME =
  process.env.NODE_ENV === 'production'
    ? STRIPE_URL_SCHEME_PROD
    : STRIPE_URL_SCHEME_DEV;
export const STRIPE_PUBLISHABLE_KEY =
  process.env.NODE_ENV === 'production'
    ? STRIPE_PUBLISHABLE_KEY_PROD
    : STRIPE_PUBLISHABLE_KEY_DEV;
export const STRIPE_MERCHANT_IDENTIFIER =
  process.env.NODE_ENV === 'production'
    ? STRIPE_MERCHANT_IDENTIFIER_PROD
    : STRIPE_MERCHANT_IDENTIFIER_DEV;
export const STRIPE_SECRET_KEY =
  process.env.NODE_ENV === 'production'
    ? STRIPE_SECRET_KEY_PROD
    : STRIPE_SECRET_KEY_DEV;
export const LUPA_MEETING_SERVICE_FEE_PERCENTAGE =
  process.env.NODE_ENV === 'production'
    ? LUPA_MEETING_SERVICE_FEE_PERCENTAGE_PROD
    : LUPA_MEETING_SERVICE_FEE_PERCENTAGE_DEV;
export const LUPA_PROGRAM_SERVICE_FEE_PERCENTAGE =
  process.env.NODE_ENV === 'production'
    ? LUPA_PROGRAM_SERVICE_FEE_PERCENTAGE_PROD
    : LUPA_PROGRAM_SERVICE_FEE_PERCENTAGE_DEV;

export const FIREBASE_API_KEY =
  process.env.NODE_ENV === 'production'
    ? FIREBASE_API_KEY_PROD
    : FIREBASE_API_KEY_DEV;
export const FIREBASE_AUTH_DOMAIN =
  process.env.NODE_ENV === 'production'
    ? FIREBASE_AUTH_DOMAIN_PROD
    : FIREBASE_AUTH_DOMAIN_DEV;
export const FIREBASE_PROJECT_ID =
  process.env.NODE_ENV === 'production'
    ? FIREBASE_PROJECT_ID_PROD
    : FIREBASE_PROJECT_ID_DEV;
export const FIREBASE_STORAGE_BUCKET =
  process.env.NODE_ENV === 'production'
    ? FIREBASE_STORAGE_BUCKET_PROD
    : FIREBASE_STORAGE_BUCKET_DEV;
export const FIREBASE_MESSAGING_SENDER_ID =
  process.env.NODE_ENV === 'production'
    ? FIREBASE_MESSAGING_SENDER_ID_PROD
    : FIREBASE_MESSAGING_SENDER_ID_DEV;
export const FIREBASE_APP_ID =
  process.env.NODE_ENV === 'production'
    ? FIREBASE_APP_ID_PROD
    : FIREBASE_APP_ID_DEV;
export const FIREBASE_MEASUREMENT_ID =
  process.env.NODE_ENV === 'production'
    ? FIREBASE_MEASUREMENT_ID_PROD
    : FIREBASE_MEASUREMENT_ID_DEV;
